In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
from sklearn.metrics import *

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("/kaggle/input/dshudhus/train (6).csv")
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert
...,...,...,...,...,...,...,...,...,...
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,18520,1.0,NaN,6.0,7.0,No,6.0,5.0,Extrovert
18521,18521,7.0,Yes,1.0,1.0,Yes,1.0,NaN,Introvert
18522,18522,NaN,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [6]:
df.isna().sum()

id                              0
Time_spent_Alone             1190
Stage_fear                   1893
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing    1149
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64

In [9]:
time_mean=df['Time_spent_Alone'].mean()
time_mean

3.1377639321564557

In [10]:
social_mean=df['Social_event_attendance'].mean()
going_mean=df['Going_outside'].mean()
friend_mean=df['Friends_circle_size'].mean()
post_mean=df['Post_frequency'].mean()

In [12]:
df['Stage_fear'].fillna("",inplace=True)
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert
...,...,...,...,...,...,...,...,...,...
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,18520,1.0,,6.0,7.0,No,6.0,5.0,Extrovert
18521,18521,7.0,Yes,1.0,1.0,Yes,1.0,NaN,Introvert
18522,18522,NaN,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [13]:
df['Drained_after_socializing'].fillna("",inplace=True)

/tmp/ipykernel_35/3212234532.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Drained_after_socializing'].fillna("",inplace=True)

In [14]:
df.columns

Index(['id', 'Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
       'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
       'Post_frequency', 'Personality'],
      dtype='object')

In [15]:
df['Time_spent_Alone'].fillna(time_mean,inplace=True)
df

/tmp/ipykernel_35/1693430247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Time_spent_Alone'].fillna(time_mean,inplace=True)
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.000000,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.000000,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.000000,Yes,1.0,0.0,,3.0,0.0,Introvert
3,3,3.000000,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.000000,No,4.0,4.0,No,13.0,NaN,Extrovert
...,...,...,...,...,...,...,...,...,...
18519,18519,3.000000,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,18520,1.000000,,6.0,7.0,No,6.0,5.0,Extrovert
18521,18521,7.000000,Yes,1.0,1.0,Yes,1.0,NaN,Introvert
18522,18522,3.137764,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,18523,1.000000,No,8.0,6.0,No,4.0,7.0,Extrovert

In [16]:
df.isna().sum()

id                              0
Time_spent_Alone                0
Stage_fear                      0
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing       0
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64

In [18]:
df.columns

Index(['id', 'Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
       'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
       'Post_frequency', 'Personality'],
      dtype='object')

In [19]:
df['Social_event_attendance'].fillna(social_mean,inplace=True)
df['Going_outside'].fillna(going_mean,inplace=True)
df['Friends_circle_size'].fillna(friend_mean,inplace=True)
df['Post_frequency'].fillna(post_mean,inplace=True)

/tmp/ipykernel_35/1541531832.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Social_event_attendance'].fillna(social_mean,inplace=True)
/tmp/ipykernel_35/1541531832.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Going_outside'].fillna(going_mean,inplace=True)
/tmp/ipykernel_35/1541531832.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Friends_circle_size'].fillna(friend_mean,inplace=True)
/tmp/ipykernel_35/1541531832.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Post_frequency'].fillna(post_mean,inplace=True)

In [20]:
df.isna().sum()

id                           0
Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [21]:
df.tail()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
18519,18519,3.000000,No,7.0,3.0,No,9.0,7.000000,Extrovert
18520,18520,1.000000,,6.0,7.0,No,6.0,5.000000,Extrovert
18521,18521,7.000000,Yes,1.0,1.0,Yes,1.0,4.982097,Introvert
18522,18522,3.137764,Yes,1.0,0.0,Yes,5.0,2.000000,Introvert
18523,18523,1.000000,No,8.0,6.0,No,4.0,7.000000,Extrovert

In [36]:
df['Stage_fear']=df['Stage_fear'].replace({'Yes':1,'No':2,"":3})
df['Drained_after_socializing']=df['Drained_after_socializing'].replace({'Yes':1,'No':2,"":3})

/tmp/ipykernel_35/2285350252.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Stage_fear']=df['Stage_fear'].replace({'Yes':1,'No':2,"":3})
/tmp/ipykernel_35/2285350252.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Drained_after_socializing']=df['Drained_after_socializing'].replace({'Yes':1,'No':2,"":3})

In [67]:
df.drop(['id'],axis=1,inplace=True)
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0.000000,2,6.0,4.0,2,15.0,5.000000,5
1,1.000000,2,7.0,3.0,2,10.0,8.000000,5
2,6.000000,1,1.0,0.0,3,3.0,0.000000,4
3,3.000000,2,7.0,3.0,2,11.0,5.000000,5
4,1.000000,2,4.0,4.0,2,13.0,4.982097,5
...,...,...,...,...,...,...,...,...
18519,3.000000,2,7.0,3.0,2,9.0,7.000000,5
18520,1.000000,3,6.0,7.0,2,6.0,5.000000,5
18521,7.000000,1,1.0,1.0,1,1.0,4.982097,4
18522,3.137764,1,1.0,0.0,1,5.0,2.000000,4
18523,1.000000,2,8.0,6.0,2,4.0,7.000000,5

In [118]:
df['Personality']=df['Personality'].replace({5:0,4:1})

In [213]:
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0.000000,2,6.0,4.0,2,15.0,5.000000,0
1,1.000000,2,7.0,3.0,2,10.0,8.000000,0
2,6.000000,1,1.0,0.0,3,3.0,0.000000,1
3,3.000000,2,7.0,3.0,2,11.0,5.000000,0
4,1.000000,2,4.0,4.0,2,13.0,4.982097,0
...,...,...,...,...,...,...,...,...
18519,3.000000,2,7.0,3.0,2,9.0,7.000000,0
18520,1.000000,3,6.0,7.0,2,6.0,5.000000,0
18521,7.000000,1,1.0,1.0,1,1.0,4.982097,1
18522,3.137764,1,1.0,0.0,1,5.0,2.000000,1
18523,1.000000,2,8.0,6.0,2,4.0,7.000000,0

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         18524 non-null  int64
 1   Time_spent_Alone           18524 non-null  float64
 2   Stage_fear                 18524 non-null  int64
 3   Social_event_attendance    18524 non-null  float64
 4   Going_outside              18524 non-null  float64
 5   Drained_after_socializing  18524 non-null  int64
 6   Friends_circle_size        18524 non-null  float64
 7   Post_frequency             18524 non-null  float64
 8   Personality                18524 non-null  int64
dtypes: float64(5), int64(4)
memory usage: 1.3 MB

In [141]:
x=df.iloc[:,:-1]
x

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,0.000000,2,6.0,4.0,2,15.0,5.000000
1,1.000000,2,7.0,3.0,2,10.0,8.000000
2,6.000000,1,1.0,0.0,3,3.0,0.000000
3,3.000000,2,7.0,3.0,2,11.0,5.000000
4,1.000000,2,4.0,4.0,2,13.0,4.982097
...,...,...,...,...,...,...,...
18519,3.000000,2,7.0,3.0,2,9.0,7.000000
18520,1.000000,3,6.0,7.0,2,6.0,5.000000
18521,7.000000,1,1.0,1.0,1,1.0,4.982097
18522,3.137764,1,1.0,0.0,1,5.0,2.000000
18523,1.000000,2,8.0,6.0,2,4.0,7.000000

In [142]:
y=df["Personality"]
y

0        0
1        0
2        1
3        0
4        0
        ..
18519    0
18520    0
18521    1
18522    1
18523    0
Name: Personality, Length: 18524, dtype: int64

In [127]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense,Dropout,BatchNormalization
from keras.callbacks import EarlyStopping

In [150]:
clf=Sequential()

In [151]:
clf.add(Dense(units=15,kernel_initializer='he_normal',activation='relu'))
clf.add(Dense(units=10,kernel_initializer='he_normal',activation='relu'))
clf.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))
clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [144]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(14819, 7) (3705, 7) (14819,) (3705,)

In [152]:
history=model=clf.fit(x_train,y_train,validation_split=0.33,batch_size=5,epochs=30)

Epoch 1/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8540 - loss: 0.7461 - val_accuracy: 0.9683 - val_loss: 0.1491
Epoch 2/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9676 - loss: 0.1565 - val_accuracy: 0.9685 - val_loss: 0.1441
Epoch 3/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9657 - loss: 0.1556 - val_accuracy: 0.9697 - val_loss: 0.1406
Epoch 4/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9661 - loss: 0.1537 - val_accuracy: 0.9701 - val_loss: 0.1435
Epoch 5/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9681 - loss: 0.1413 - val_accuracy: 0.9699 - val_loss: 0.1355
Epoch 6/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9707 - loss: 0.1336 - val_accuracy: 0.9708 - val_loss: 0.1342
Epoch 7/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9660 - loss: 0.1478 - val_accuracy: 0.9701 - val_loss: 0.1338
Epoch 8/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9637 - loss: 0.1517 - val_accuracy: 0.9689 - val_loss: 0.1359
Epoch 9/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9669 - loss: 0.1425 - val_accuracy: 0.9701 - val_loss: 0.1345
Epoch 10/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9653 - loss: 0.1499 - val_accuracy: 0.9706 - val_loss: 0.1291
Epoch 11/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9657 - loss: 0.1422 - val_accuracy: 0.9701 - val_loss: 0.1285
Epoch 12/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9658 - loss: 0.1417 - val_accuracy: 0.9706 - val_loss: 0.1281
Epoch 13/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9706 - loss: 0.1243 - val_accuracy: 0.9706 - val_loss: 0.1288
Epoch 14/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9679 - loss: 0.1345 - val_accuracy: 0.9706 - val_loss: 0.1293
Epoch 15/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9660 - loss: 0.1420 - val_accuracy: 0.9708 - val_loss: 0.1295
Epoch 16/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9696 - loss: 0.1286 - val_accuracy: 0.9714 - val_loss: 0.1278
Epoch 17/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9686 - loss: 0.1317 - val_accuracy: 0.9706 - val_loss: 0.1273
Epoch 18/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9680 - loss: 0.1362 - val_accuracy: 0.9712 - val_loss: 0.1320
Epoch 19/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9658 - loss: 0.1390 - val_accuracy: 0.9706 - val_loss: 0.1333
Epoch 20/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9671 - loss: 0.1380 - val_accuracy: 0.9712 - val_loss: 0.1290
Epoch 21/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9685 - loss: 0.1327 - val_accuracy: 0.9708 - val_loss: 0.1290
Epoch 22/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9679 - loss: 0.1344 - val_accuracy: 0.9710 - val_loss: 0.1316
Epoch 23/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9697 - loss: 0.1263 - val_accuracy: 0.9712 - val_loss: 0.1310
Epoch 24/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9670 - loss: 0.1374 - val_accuracy: 0.9710 - val_loss: 0.1274
Epoch 25/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9669 - loss: 0.1379 - val_accuracy: 0.9712 - val_loss: 0.1276
Epoch 26/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9680 - loss: 0.1359 - val_accuracy: 0.9712 - val_loss: 0.1295
Epoch 27/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9637 - loss: 0.1477 - val_accuracy: 0.9714 - val_loss: 0.1287
Epoch 28/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9671 - loss: 0.1356 - val_accuracy: 0.9710 - val_loss: 0.1271
Epoch 29/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9673 - loss: 0.1329 - val_accuracy: 0.9716 - val_loss: 0.1272
Epoch 30/30
1986/1986 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9667 - loss: 0.1396 - val_accuracy: 0.9714 - val_loss: 0.1265

In [156]:
y_test

13209    0
2740     0
10249    0
7608     0
10528    0
        ..
3269     0
15214    1
1127     0
11368    0
17737    0
Name: Personality, Length: 3705, dtype: int64

In [158]:
y_pred=clf.predict(x_test)
y_pred

116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.02352056],
       [0.01402134],
       [0.0249005 ],
       ...,
       [0.0169903 ],
       [0.02728414],
       [0.01285472]], dtype=float32)

In [165]:
y_pred_binary

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [159]:
y_pred_binary = (y_pred > 0.5).astype(int)
print("Accuracy:", accuracy_score(y_test, y_pred_binary))

Accuracy: 0.9689608636977058

In [178]:
callback=EarlyStopping(monitor='accuracy',min_delta=0.1,patience=4,verbose=1,mode='auto',baseline=None,restore_best_weights=False)

In [179]:
history=clf.fit(x_train,y_train,epochs=100,validation_data=(x_train,y_train),callbacks=callback)

Epoch 1/100
464/464 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9692 - loss: 0.1325 - val_accuracy: 0.9691 - val_loss: 0.1297
Epoch 2/100
464/464 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9671 - loss: 0.1348 - val_accuracy: 0.9692 - val_loss: 0.1281
Epoch 3/100
464/464 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9692 - loss: 0.1290 - val_accuracy: 0.9692 - val_loss: 0.1300
Epoch 4/100
464/464 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9691 - loss: 0.1290 - val_accuracy: 0.9690 - val_loss: 0.1283
Epoch 5/100
464/464 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9713 - loss: 0.1220 - val_accuracy: 0.9688 - val_loss: 0.1281
Epoch 5: early stopping

In [180]:
y_pred=clf.predict(x_test)
y_pred

116/116 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.04400105],
       [0.02192828],
       [0.05165177],
       ...,
       [0.02286576],
       [0.0474417 ],
       [0.023331  ]], dtype=float32)

In [181]:
y_pred_binary = (y_pred > 0.5).astype(int)
print("Accuracy:", accuracy_score(y_test, y_pred_binary))

Accuracy: 0.9692307692307692

In [182]:
test=pd.read_csv("/kaggle/input/dshudhus/test (6).csv")
test

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,18524,3.0,No,7.0,4.0,No,6.0,NaN
1,18525,NaN,Yes,0.0,0.0,Yes,5.0,1.0
2,18526,3.0,No,5.0,6.0,No,15.0,9.0
3,18527,3.0,No,4.0,4.0,No,5.0,6.0
4,18528,9.0,Yes,1.0,2.0,Yes,1.0,1.0
...,...,...,...,...,...,...,...,...
6170,24694,3.0,No,5.0,5.0,No,9.0,6.0
6171,24695,8.0,Yes,2.0,1.0,Yes,0.0,0.0
6172,24696,2.0,No,4.0,3.0,No,9.0,7.0
6173,24697,3.0,No,4.0,4.0,No,11.0,9.0
6174,24698,NaN,Yes,1.0,1.0,Yes,1.0,0.0

In [184]:
test.isna().sum()

id                             0
Time_spent_Alone             425
Stage_fear                   598
Social_event_attendance      397
Going_outside                466
Drained_after_socializing    432
Friends_circle_size          350
Post_frequency               408
dtype: int64

In [183]:
social_mean=test['Social_event_attendance'].mean()
going_mean=test['Going_outside'].mean()
friend_mean=test['Friends_circle_size'].mean()
post_mean=test['Post_frequency'].mean()
time_mean=test['Time_spent_Alone'].mean()

In [185]:
test['Stage_fear'].fillna("",inplace=True)
test['Drained_after_socializing'].fillna("",inplace=True)

/tmp/ipykernel_35/3708326444.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Stage_fear'].fillna("",inplace=True)
/tmp/ipykernel_35/3708326444.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Drained_after_socializing'].fillna("",inplace=True)

In [186]:
test

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,18524,3.0,No,7.0,4.0,No,6.0,NaN
1,18525,NaN,Yes,0.0,0.0,Yes,5.0,1.0
2,18526,3.0,No,5.0,6.0,No,15.0,9.0
3,18527,3.0,No,4.0,4.0,No,5.0,6.0
4,18528,9.0,Yes,1.0,2.0,Yes,1.0,1.0
...,...,...,...,...,...,...,...,...
6170,24694,3.0,No,5.0,5.0,No,9.0,6.0
6171,24695,8.0,Yes,2.0,1.0,Yes,0.0,0.0
6172,24696,2.0,No,4.0,3.0,No,9.0,7.0
6173,24697,3.0,No,4.0,4.0,No,11.0,9.0
6174,24698,NaN,Yes,1.0,1.0,Yes,1.0,0.0

In [187]:
test.isna().sum()

id                             0
Time_spent_Alone             425
Stage_fear                     0
Social_event_attendance      397
Going_outside                466
Drained_after_socializing      0
Friends_circle_size          350
Post_frequency               408
dtype: int64

In [188]:
test['Stage_fear']=test['Stage_fear'].replace({'Yes':1,'No':2,"":3})
test['Drained_after_socializing']=test['Drained_after_socializing'].replace({'Yes':1,'No':2,"":3})

/tmp/ipykernel_35/3655921198.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Stage_fear']=test['Stage_fear'].replace({'Yes':1,'No':2,"":3})
/tmp/ipykernel_35/3655921198.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Drained_after_socializing']=test['Drained_after_socializing'].replace({'Yes':1,'No':2,"":3})

In [189]:
test['Social_event_attendance'].fillna(social_mean,inplace=True)
test['Going_outside'].fillna(going_mean,inplace=True)
test['Friends_circle_size'].fillna(friend_mean,inplace=True)
test['Post_frequency'].fillna(post_mean,inplace=True)
test['Time_spent_Alone'].fillna(time_mean,inplace=True)

/tmp/ipykernel_35/1298530853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Social_event_attendance'].fillna(social_mean,inplace=True)
/tmp/ipykernel_35/1298530853.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Going_outside'].fillna(going_mean,inplace=True)
/tmp/ipykernel_35/1298530853.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Friends_circle_size'].fillna(friend_mean,inplace=True)
/tmp/ipykernel_35/1298530853.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Post_frequency'].fillna(post_mean,inplace=True)
/tmp/ipykernel_35/1298530853.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Time_spent_Alone'].fillna(time_mean,inplace=True)

In [190]:
test.isna().sum()

id                           0
Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
dtype: int64

In [191]:
test

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,18524,3.00000,2,7.0,4.0,2,6.0,5.028958
1,18525,3.11687,1,0.0,0.0,1,5.0,1.000000
2,18526,3.00000,2,5.0,6.0,2,15.0,9.000000
3,18527,3.00000,2,4.0,4.0,2,5.0,6.000000
4,18528,9.00000,1,1.0,2.0,1,1.0,1.000000
...,...,...,...,...,...,...,...,...
6170,24694,3.00000,2,5.0,5.0,2,9.0,6.000000
6171,24695,8.00000,1,2.0,1.0,1,0.0,0.000000
6172,24696,2.00000,2,4.0,3.0,2,9.0,7.000000
6173,24697,3.00000,2,4.0,4.0,2,11.0,9.000000
6174,24698,3.11687,1,1.0,1.0,1,1.0,0.000000

In [193]:
id=test.id
id

0       18524
1       18525
2       18526
3       18527
4       18528
        ...
6170    24694
6171    24695
6172    24696
6173    24697
6174    24698
Name: id, Length: 6175, dtype: int64

In [196]:
test.drop('id',axis=1,inplace=True)

In [197]:
test

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency
0,3.00000,2,7.0,4.0,2,6.0,5.028958
1,3.11687,1,0.0,0.0,1,5.0,1.000000
2,3.00000,2,5.0,6.0,2,15.0,9.000000
3,3.00000,2,4.0,4.0,2,5.0,6.000000
4,9.00000,1,1.0,2.0,1,1.0,1.000000
...,...,...,...,...,...,...,...
6170,3.00000,2,5.0,5.0,2,9.0,6.000000
6171,8.00000,1,2.0,1.0,1,0.0,0.000000
6172,2.00000,2,4.0,3.0,2,9.0,7.000000
6173,3.00000,2,4.0,4.0,2,11.0,9.000000
6174,3.11687,1,1.0,1.0,1,1.0,0.000000

In [210]:
y_pred=clf.predict(test)
y_pred.flatten()

193/193 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([0.01208102, 0.9646951 , 0.03086449, ..., 0.01148775, 0.02455668,
       0.9547594 ], dtype=float32)

In [211]:
y_pred_binary = (y_pred.flatten() > 0.5).astype(int)
y_pred_binary

array([0, 1, 0, ..., 0, 0, 1])

In [202]:
id

0       18524
1       18525
2       18526
3       18527
4       18528
        ...
6170    24694
6171    24695
6172    24696
6173    24697
6174    24698
Name: id, Length: 6175, dtype: int64

In [212]:
sub_df=pd.DataFrame({'id':id,'Personality':y_pred_binary})
sub_df

         id  Personality
0     18524            0
1     18525            1
2     18526            0
3     18527            0
4     18528            1
...     ...          ...
6170  24694            0
6171  24695            1
6172  24696            0
6173  24697            0
6174  24698            1

[6175 rows x 2 columns]

In [214]:
sub_df['Personality']=sub_df['Personality'].replace({0:'Extrovert',1:'Introvert'})
sub_df

         id Personality
0     18524   Extrovert
1     18525   Introvert
2     18526   Extrovert
3     18527   Extrovert
4     18528   Introvert
...     ...         ...
6170  24694   Extrovert
6171  24695   Introvert
6172  24696   Extrovert
6173  24697   Extrovert
6174  24698   Introvert

[6175 rows x 2 columns]

In [218]:
sub_df.to_csv('submit_df.csv',index=False)